# Generated by Django 3.2.8 on 2021-10-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Titulo de la película')),
                ('sinopsis', models.TextField(max_length=1000, verbose_name='Sinopsis')),
                ('duracion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Indicar el tiempo en horas')),
                ('tamanio', models.CharField(max_length=50, verbose_name='Definir tamaño de la película')),
                ('poster', models.ImageField(null=True, upload_to='posters/peliculas/', verbose_name='Póster de la película')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
    ]
