# Generated by Django 3.2.8 on 2021-10-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(max_length=600, verbose_name='Descripción'),
        ),
    ]
