# Generated by Django 3.2.8 on 2021-10-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernadero', '0002_alter_plant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del médico')),
                ('apellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('especialidad', models.CharField(choices=[('esp1', 'Pediatría'), ('esp2', 'Ortodoncia'), ('esp3', 'Partos'), ('esp4', 'Cirujano'), ('esp5', 'Quiropráctico')], max_length=15, verbose_name='Elige especialidad')),
                ('telefono', models.CharField(max_length=15, verbose_name='Ingrese teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
    ]
